spring.application.name=photography

# Aiven MySQL
spring.datasource.url=jdbc:mysql://photography-mysql-haripriya02122003-77a2.l.aivencloud.com:17172/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Server
server.port=${PORT:8080}

# Brevo
brevo.api.key=${BREVO_API_KEY}
